### ISSUE TITLE
Allow storage of enrichment kit targets

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#19]
**Is your feature request related to a problem? Please describe.**
Right now the enrichment kit is not known for each case. A prerequisite is making the kits known to VarFish.

**Describe the solution you'd like**
This consists of various things:

- create a new site-wide app that allows this registration
- provide a working way of registering new kits
- provide the actual BED files (done in the downloader)

**Describe alternatives you've considered**
N/A

**Additional context**
- Data download: https://github.com/bihealth/varfish-db-downloader/issues/52
- SRA provides the following sample sheet that contains some controlled vocabulary [XLSX file](https://ftp-trace.ncbi.nlm.nih.gov/sra/metadata_table/SRA_metadata_acc.xlsx)
- Follow-Up: #505

**Comment by holtgrewe** [comment]
UCSC genome browser provides the following probesets

https://genome.ucsc.edu/cgi-bin/hgTrackUi?db=hg19&g=exomeProbesets

```
AmpliSeq Target	 Illumina - AmpliSeq Exome Panel Target Regions 
IDT xGen v1.0 P	 IDT - xGen Exome Research Panel V1.0 Probes 
IDT xGen V1.0 T	 IDT - xGen Exome Research Panel V1.0 Target Regions 
IDT xGen V2.0 P	 IDT - xGen Exome Research Panel V2.0 Probes 
IDT xGen V2.0 T	 IDT - xGen Exome Research Panel V2.0 Target Regions 
KAPA Hyper P	 Roche - KAPA HyperExome Capture Probe Footprint 
KAPA Hyper T	 Roche - KAPA HyperExome Primary Target Regions 
MGI Easy V4 T	 MGI - Easy Exome Capture V4 Target Regions 
MGI Easy V5 T	 MGI - Easy Exome Capture V5 Target Regions 
Nextera DNA V1.2 T	 Illumina - Nextera DNA Exome V1.2 Target Regions 
Nextera Rapid Exp. T	 Illumina - Nextera Rapid Capture Expanded Exome Target Regions 
Nextera Rapid T	 Illumina - Nextera Rapid Capture Exome Target Regions 
Nextera Rapid V1.2 T	 Illumina - Nextera Rapid Capture Exome V1.2 Target Regions 
SeqCap EZ Med P	 Roche - SeqCap EZ MedExome Capture Probe Footprint 
SeqCap EZ Med T	 Roche - SeqCap EZ MedExome Empirical Target Regions 
SeqCap EZ Med+Mito P	 Roche - SeqCap EZ MedExome + Mito Capture Probe Footprint 
SeqCap EZ Med+Mito T	 Roche - SeqCap EZ MedExome + Mito Empirical Target Regions 
SeqCap EZ V3 P	 Roche - SeqCap EZ Exome V3 Capture Probe Footprint 
SeqCap EZ V3 T	 Roche - SeqCap EZ Exome V3 Primary Target Regions 
SeqCap EZ V3 UTR P	 Roche - SeqCap EZ Exome V3 + UTR Capture Probe Footprint 
SeqCap EZ V3 UTR T	 Roche - SeqCap EZ Exome V3 + UTR Primary Target Regions 
SureSel. Clinical P	 Agilent - SureSelect Clinical Research Exome Covered by Probes 
SureSel. Clinical T	 Agilent - SureSelect Clinical Research Exome Target Regions 
SureSel. Clinical V2 P	 Agilent - SureSelect Clinical Research Exome V2 Covered by Probes 
SureSel. Clinical V2 T	 Agilent - SureSelect Clinical Research Exome V2 Target 
SureSel. Focused P	 Agilent - SureSelect Focused Exome Covered by Probes 
SureSel. Focused T	 Agilent - SureSelect Focused Exome Target Regions 
SureSel. V4 P	 Agilent - SureSelect All Exon V4 Covered by Probes 
SureSel. V4 T	 Agilent - SureSelect All Exon V4 Target Regions 
SureSel. V4+UTR P	 Agilent - SureSelect All Exon V4 + UTRs Covered by Probe 
SureSel. V4+UTR T	 Agilent - SureSelect All Exon V4 + UTRs Target Regions 
SureSel. V5 P	 Agilent - SureSelect All Exon V5 Covered by Probes 
SureSel. V5 T	 Agilent - SureSelect All Exon V5 Target Regions 
SureSel. V5+UTR P	 Agilent - SureSelect All Exon V5 + UTRs Covered by Probes 
SureSel. V5+UTR T	 Agilent - SureSelect All Exon V5 + UTRs Target Regions 
SureSel. V6 P	 Agilent - SureSelect All Exon V6 r2 Covered by Probes 
SureSel. V6 T	 Agilent - SureSelect All Exon V6 r2 Target Regions 
SureSel. V6+COSMIC P	 Agilent - SureSelect All Exon V6 + COSMIC r2 Covered by Probes 
SureSel. V6+COSMIC T	 Agilent - SureSelect All Exon V6 + COSMIC r2 Target Regions 
SureSel. V6+UTR P	 Agilent - SureSelect All Exon V6 + UTR r2 Covered by Probes 
SureSel. V7 P	 Agilent - SureSelect All Exon V7 Covered by Probes 
SureSel. V7 T	 Agilent - SureSelect All Exon V7 Target Regions 
SureSelect SureSel. V6+UTR T	 Agilent - SureSelect All Exon V6 + UTR r2 Target Regions 
TruSeq DNA V1.2 T	 Illumina - TruSeq DNA Exome V1.2 Target Regions 
TruSeq Rapid v1.2 T	 Illumina - TruSeq Rapid Exome V1.2 Target Regions Regions 
TruSight One Exp. V2.0 T	 Illumina - TruSight ONE Expanded V2.0 Target Regions 
TruSight One V1.1 T	 Illumina - TruSight ONE V1.1 Target Regions 
TruSight Target	 Illumina - TruSight Exome Target Regions 
Twist Compr. T	 Twist - Comprehensive Exome Panel Target Regions 
Twist Core T	 Twist - Core Exome Panel Target Regions 
Twist Exome 2.0	 Twist - Exome 2.0 Panel Target Regions 
Twist RefSeq T	 Twist - RefSeq Exome Panel Target Regions 
```

https://genome.ucsc.edu/cgi-bin/hgTrackUi?db=hg38&g=exomeProbesets

```
IDT xGen V2 P	 IDT - xGen Exome Research Panel V2 Probes 
IDT xGen V2 T	 IDT - xGen Exome Research Panel V2 Target Regions 
KAPA Hyper P	 Roche - KAPA HyperExome Capture Probe Footprint 
KAPA Hyper T	 Roche - KAPA HyperExome Primary Target Regions 
SeqCap EZ Med P	 Roche - SeqCap EZ MedExome Capture Probe Footprint 
SeqCap EZ Med T	 Roche - SeqCap EZ MedExome Empirical Target Regions 
SeqCap EZ Med+Mito P	 Roche - SeqCap EZ MedExome + Mito Capture Probe Footprint 
SeqCap EZ Med+Mito T	 Roche - SeqCap EZ MedExome + Mito Empirical Target Regions 
SureSel. Clinical V2 P	 Agilent - SureSelect Clinical Research Exome V2 Covered by Probes 
SureSel. Clinical V2 T	 Agilent - SureSelect Clinical Research Exome V2 Target Regions 
SureSel. Focused P	 Agilent - SureSelect Focused Exome Covered by Probes 
SureSel. Focused T	 Agilent - SureSelect Focused Exome Target Regions 
SureSel. V4+UTR P	 Agilent - SureSelect All Exon V4 + UTRs Covered by Probes 
SureSel. V4+UTR T	 Agilent - SureSelect All Exon V4 + UTRs Target Regions 
SureSel. V5+UTR P	 Agilent - SureSelect All Exon V5 + UTRs Covered by Probes 
SureSel. V5+UTR T	 Agilent - SureSelect All Exon V5 + UTRs Target Regions 
SureSel. V6 +UTR T	 Agilent - SureSelect All Exon V6 + UTR r2 Target Regions 
SureSel. V6 P	 Agilent - SureSelect All Exon V6 r2 Covered by Probes 
SureSel. V6 T	 Agilent - SureSelect All Exon V6 r2 Target Regions 
SureSel. V6+COSMIC P	 Agilent - SureSelect All Exon V6 + COSMIC r2 Covered by Probes 
SureSel. V6+COSMIC T	 Agilent - SureSelect All Exon V6 + COSMIC r2 Target Regions 
SureSel. V6+UTR P	 Agilent - SureSelect All Exon V6 + UTR r2 Covered by Probes 
SureSel. V7 P	 Agilent - SureSelect All Exon V7 Covered by Probes 
SureSel. V7 T	 Agilent - SureSelect All Exon V7 Target Regions 
Twist Compr. T	 Twist - Comprehensive Exome Panel Target Regions 
Twist Core T	 Twist - Bioscience - Core Exome Panel Target Regions 
Twist Exome 2.0	 Twist - Exome 2.0 Panel Target Regions 
Twist RefSeq T	 Twist - RefSeq Exome Panel Target Regions 
```

**Comment by holtgrewe** [comment]
SRA provides the following sample sheet that contains some controlled vocabulary:

- https://ftp-trace.ncbi.nlm.nih.gov/sra/metadata_table/SRA_metadata_acc.xlsx

**Comment by holtgrewe** [comment]
GA4GH Pedigree standard

- https://github.com/GA4GH-Pedigree-Standard/pedigree

**Comment by holtgrewe** [comment]
A slightly extended phenopackets that captures the most important information of a case manifest.

```yaml
family:
  xSodarUuid: SODAR_UUID
  id: CASE_NAME
  proband:
    id: IDENTIFIER_INDEX
    subject:
      id: IDENTIFIER_INDEX
      alternateIds:
        - ns:uri
      sex: MALE # FEMALE / OTHER_SEX / UNKNOWN_SEX
      karyotypic_sex: UNKNOWN_KARYOTYPE  # cf. https://phenopacket-schema.readthedocs.io/en/latest/karyotypicsex.html#rstkaryotypicsex
    phenotypicFeatures:
      - type:
          id: "HP:0012469"
          label: "Infantile spasms"
        excluded: false
        modifiers:
          - id: "HP:0031796"
            label: "Recurrent"
    measurements:
      # we only allow one measurement in VarFish 2.0
      - description: WGS / WES / Panel-seq of
        assay:
          id: NCIT:C158253
          label: Targeted Genome Sequencing
          # alternative #1
          #id: NCIT:C101295
          #label: Whole Exome Sequencing
          # alternative #2
          #id: NCIT:C101294
          #label: Whole Genome Sequencing
        measurement_value:
          value:
            id: NCIT:C171177
            label: Sequencing Data File
        time_observed:  # optional
          timestamp: the timestamp
    diseases:
      - term: OMIM:xxx
        excluded: false
    files: # FILES FOR PROBAND
      - uri: s3://...
        individualToFileIdentifiers:
          IDENTIFIER_INDEX: identifier in file
        fileAttributes:
          genomeAssembly: GRCh38  # GRCh37
          fileFormat: vcf  # BAM etc.
          description: free-text description
        # TODO: more file examples, possibly extended attributes
    metadata: # COPY AND PASTE FROM BELOW
  relatives:
    - # ... list of phenopackets
  pedigree:
    persons:
      - familyId: FAM
        individualId: IDENTIFIER_INDEX
        patenralId: 0
        maternalId: 0
        sex: MALE
        affectedStatus: UNAFFECTED
  files:  # FILES FOR WHOLE FAMILY
    - uri: ...
  metadata:
    created: 2019-07-21T00:25:54.662Z
    createdBy: Peter R.
    resources:
      - id: hp
        name: human phenotype ontology
        url: http://purl.obolibrary.org/obo/hp.owl
        version: 2018-03-08
        namespacePrefix: HP
        iriPrefix: hp
      - id: geno
        name: Genotype Ontology
        url: http://purl.obolibrary.org/obo/geno.owl
        version: 19-03-2018
        namespacePrefix: GENO
        iriPrefix: geno
      - id: pubmed
        name: PubMed
        url: https://www.ncbi.nlm.nih.gov/pubmed/
        namespacePrefix: PMID
      - id: orphanet
        name: orphanet rare disease ontology
        url: http://www.orpha.net/
        namespacePrefix: ORPHA
        iriPrefix: orpha
      - id: omim
        name: Online Mendelian Inheritance in Man
        url: http://www.omim.org/
        namespacePrefix: OMIM
        iriPrefix: omim
      - id: ncit
        name: National Cancer Institute Thesaurus
        url: https://bioportal.bioontology.org/ontologies/NCIT/
        namespacePrefix: NCIT
        iriPrefix: ncit
    phenopacketSchemaVersion: 2.0
```
