### ISSUE TITLE
Design "case manifest" file format

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#505]
**Is your feature request related to a problem? Please describe.**
We can currently (only) provide a PED file for describing a case. It would be very helpful to augment this as we currently already store information in VarFish that cannot be encoded in a canonical [PLINK PED file](https://zzz.bwh.harvard.edu/plink/data.shtml). This means we cannot export into the same format that we import from and it would also be nice to import with more information as well.

**Describe the solution you'd like**
Design a "case manifest" format that describes the **relevant** aspects of a case. We should reuse (community) standard data formats where possible; including:

- [Phenopackets 2.0 Format](https://phenopacket-schema.readthedocs.io/en/v2/)

**Describe alternatives you've considered**
N/A

**Additional context**
- [https://zzz.bwh.harvard.edu/plink/data.shtml](PLINK PED file format description)

**Comment by holtgrewe** [comment]
**Phenopackets documentation**

- https://phenopacket-schema.readthedocs.io/en/latest/index.html

This includes:

- pedigree: https://phenopacket-schema.readthedocs.io/en/latest/pedigree.html
    - note: need to add `x-xy-karyotype` for gonosomal karyotype

**GA4GH Pedigree standard**

- https://github.com/GA4GH-Pedigree-Standard/pedigree

**Proposal**

Phenopacket capturing most aspects. Phenopacket authors recommend to use file annotation for capturing sequencing details.

```yaml
family:
  # case name is in family
  id: SODAR_UUID
  proband:
    id: IDENTIFIER_INDEX
    subject:
      id: IDENTIFIER_INDEX
      alternateIds:
        - ns:uri
      sex: MALE # FEMALE / OTHER_SEX / UNKNOWN_SEX
      karyotypic_sex: UNKNOWN_KARYOTYPE  # cf. https://phenopacket-schema.readthedocs.io/en/latest/karyotypicsex.html#rstkaryotypicsex
    phenotypicFeatures:
      - type:
          id: "HP:0012469"
          label: "Infantile spasms"
        excluded: false
        modifiers:
          - id: "HP:0031796"
            label: "Recurrent"
    measurements:
      # we only allow one measurement in VarFish 2.0
      - description: WGS / WES / Panel-seq of
        assay:
          id: NCIT:C158253
          label: Targeted Genome Sequencing
          # alternative #1
          #id: NCIT:C101295
          #label: Whole Exome Sequencing
          # alternative #2
          #id: NCIT:C101294
          #label: Whole Genome Sequencing
        measurement_value:
          value:
            id: NCIT:C171177
            label: Sequencing Data File
        time_observed:  # optional
          timestamp: the timestamp
    diseases:
      - term: OMIM:xxx
        excluded: false
    files: # FILES FOR PROBAND
      - uri: s3://...
        individualToFileIdentifiers:
          IDENTIFIER_INDEX: identifier in file
        fileAttributes:
          genomeAssembly: GRCh38  # GRCh37
          fileFormat: vcf  # BAM etc.
          description: free-text description
        # TODO: more file examples, possibly extended attributes
    metadata: # COPY AND PASTE FROM BELOW
  relatives:
    - # ... list of phenopackets
  pedigree:
    persons:
      - familyId: FAM
        individualId: IDENTIFIER_INDEX
        patenralId: 0
        maternalId: 0
        sex: MALE
        affectedStatus: UNAFFECTED
  files:  # FILES FOR WHOLE FAMILY
    - uri: ...
  metadata:
    created: 2019-07-21T00:25:54.662Z
    createdBy: Peter R.
    resources:
      - id: hp
        name: human phenotype ontology
        url: http://purl.obolibrary.org/obo/hp.owl
        version: 2018-03-08
        namespacePrefix: HP
        iriPrefix: hp
      - id: geno
        name: Genotype Ontology
        url: http://purl.obolibrary.org/obo/geno.owl
        version: 19-03-2018
        namespacePrefix: GENO
        iriPrefix: geno
      - id: pubmed
        name: PubMed
        url: https://www.ncbi.nlm.nih.gov/pubmed/
        namespacePrefix: PMID
      - id: orphanet
        name: orphanet rare disease ontology
        url: http://www.orpha.net/
        namespacePrefix: ORPHA
        iriPrefix: orpha
      - id: omim
        name: Online Mendelian Inheritance in Man
        url: http://www.omim.org/
        namespacePrefix: OMIM
        iriPrefix: omim
      - id: ncit
        name: National Cancer Institute Thesaurus
        url: https://bioportal.bioontology.org/ontologies/NCIT/
        namespacePrefix: NCIT
        iriPrefix: ncit
    phenopacketSchemaVersion: 2.0
```
